### ISSUE TITLE
The background images are not displayed properly in Apple devices.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#10]
Description: 
The background images are not displayed properly in apple devices, using Safari or Google Chrome browsers.
 
-Env:
Device: Iphone 7, ipad pro
Google Chrome Version 58.0.30.29.113
Safari 10.3
Firefox 7.2(2672)
 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Review the site
 
CURRENT RESULT: 
==================== 
 The background images are not displayed properly in Apple devices.
https://www.screencast.com/t/ab9vedVBw 
https://www.screencast.com/t/6Oi9augJ 
https://www.screencast.com/t/qWfvupxMZ  
https://www.screencast.com/t/6Oi9augJ 

 
EXPECTED RESULT: 
==================== 
 The background images should be displayed properly in Apple devices.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build b0bc526.
