### ISSUE TITLE
The “collapse and expand” sign is overlapping some text of the questions in the FAQ section.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#11]
Description: 
The “collapse and expand” sign is overlapping some text of the questions in the FAQ section.
 
-Env:
Device: Android 7.1.1 
Google Chrome Version 58.0.30.29.83
Mozilla Firefox 53.0.2
Device: Iphone 7 plus
Safari 10.3
 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the FAQ section.
3. Review the questions section
 
CURRENT RESULT: 
==================== 
The “collapse and expand” sign is overlapping text of the questions in the FAQ section.
https://screencast.com/t/7P8UvuWzfLgD 
https://www.screencast.com/t/v02gKNvew 
 
EXPECTED RESULT: 
==================== 
The “collapse and expand” sign should not overlapped text of the questions in the FAQ section.

**Comment by LorenzoRodriguezRivetlogic** [comment]
fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build f93b1a9.
