### ISSUE TITLE
The Video preview image is not displayed in mobile browsers.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#12]
Description: The Video preview is not displayed in mobile browsers.
 
-Env:
Device: Android 7.1.1 
Google Chrome Version 58.0.30.29.83
Mozilla Firefox 53.0.2
 
Device: Iphone 7 IOS 10.3
Google Chrome Version 58.0.30.29.113
Safari IOS 10.3
 
 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the “Video ” section.
https://www.screencast.com/t/BRyD540Xwi 
https://www.screencast.com/t/zNf4AwPoAi 
https://www.screencast.com/t/9wkGr2mm
 
CURRENT RESULT: 
==================== 
The Video preview image is not displayed in mobile browsers.
 
EXPECTED RESULT: 
==================== 
The Video preview image should be displayed in mobile browsers.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Please test again using the recent version of crafter.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 3753745.
