### ISSUE TITLE
The Video in the “Watch Video” section can not be played in Apple mobile devices

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#13]
Description: 
The Video in the “Watch Video” section can not be played in Apple mobile devices
 
-Env:
Device: Iphone 7 
Google Chrome Version 55.0.2883.79
Safari IOS 10.3
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the “Watch Video ” section.
 
CURRENT RESULT: 
==================== 
 The Video in the “Watch Video” section can not be played in Apple mobile devices
 https://www.screencast.com/t/50Hv1slvJ5f 

EXPECTED RESULT: 
==================== 
 The Video in the “Watch Video” section should be played properly in Apple mobile devices.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Please test again using the recent version of crafter.

**Comment by juacamar** [comment]
Bug verified and closed as fixed in 3753745.
