### ISSUE TITLE
The “intro” section buttons are not displayed in mobile devices.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#14]
Description:  
The “intro” section buttons are not displayed in mobile devices.
 
-Env:
Device: Android 7.1.1 
Google Chrome Version 55.0.2883.79
Mozilla Firefox 53.0.2
 
Device: Iphone 7
Google Chrome Version 58.0.30.29.113
Safari IOS 10.3
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Review the “Intro” Section 
 
*Note: In the template from templatemo.com, the site only displays the “Register Now” button in mobile devices.
 
CURRENT RESULT: 
==================== 
The “intro” section buttons are not displayed in mobile devices.
https://www.screencast.com/t/0Yos3nYkci4K 
 
EXPECTED RESULT: 
==================== 
 The “intro” section buttons should be displayed in mobile devices.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build b0bc526.
