### ISSUE TITLE
The input fields in the “Register Here” and “Keep In Touch”sections does not have any format validation.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#15]
Description:  
When the user fill out the inputs the application does not validate if the introduced data has the correct format for the field.
 
-Env:
Device: Android 7.1.1 
Google Chrome Version 55.0.2883.79
Mozilla Firefox 53.0.2
 
Device: Iphone 7
Google Chrome Version 58.0.30.29.113
Safari IOS 10.3
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the “Register” section.
3 Fill out the fields with the next text.
	First name: leave in blank 
	Last Name: leave in blank 
	Phone Number: leave in blank 
	Email: juan.com
4.Click on the Register Button.
 
*Same test for the “Keep In Touch” section.
 
CURRENT RESULT: 
==================== 
The application allows the user to registered successfully by displaying a “Your request has been processed correctly.” message, although some fields are with no data and the email has an incorrect format.
 
EXPECTED RESULT: 
==================== 
 The application should not allow the user to register, unless all the fields are filled out and have the correct format.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build b0bc526.
