### ISSUE TITLE
The application allows the user to expand the “Message” text area in the keep in touch section without limits, causing that the page is not displayed properly.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#23]
Description: 
When the user expands a lot  the “Message” text area in the keep in touch section the page is not displayed properly.

-Env:
Device:MacBook Pro
Safari Version 10.1.1 (10603.2.5)
Google Chrome Version 58.0.3029.110 (64-bit)
Firefox 54.0 (64-bit)

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the keep in touch section
3. Expand  the “Message” text area.

CURRENT RESULT: 
==================== 
The application allows the user to expand the “Message” text area in the keep in touch section without limits, causing that the page is not displayed properly.
https://www.screencast.com/t/My8FSVKPS 

EXPECTED RESULT: 
==================== 
The application should not  allow the user to expand the “Message” text area in the keep in touch section or should limit how much the user expand the text area, so the page is never displayed improperly.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build c637e86.
