### ISSUE TITLE
The “Programs” tabs are not displayed properly.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#4]
Description:
 When the application have a lot of (Tab Names)  and more rows are needed to display the tabs, the tabs before the first row are not displayed properly.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. On the site bar, locate the components section.
3. Click on the edit button of the “Programs“  component.
4. On the Programs Details section add 10 new programs.
	Eg. Program 1, Program 2 
7. Click on the Save and Close Button.
8. Go to the programs section preview and click on the tabs.
 

CURRENT RESULT: 
==================== 
The “Programs” tabs are not displayed properly.
https://screencast.com/t/UVBamq16Tjx 
 
EXPECTED RESULT: 
==================== 
The “Programs” tabs should be displayed properly.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build f2ef5e6.
