### ISSUE TITLE
The application is not cleaning the fields when a registration is made.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#5]
Description: 
The application is not cleaning the fields when a registration is made.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the “Register” section.
3. Fill out all the fields
4. Click on the Register Button.
 
CURRENT RESULT: 
==================== 
The registration was done correctly, but the fields were not cleared after clicking the register button.
https://www.screencast.com/t/7YB539A1 
 
EXPECTED RESULT: 
==================== 
The registration was done correctly, but the fields should be cleared after clicking the register button.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build f2ef5e6.
