### ISSUE TITLE
The “Sponsor” logos are not displayed properly.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#6]
Description: 
When the sponsor logos are from different sizes, they are not displayed properly.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. On the site bar, locate the components section.
3. Click on the edit button of the “Sponsors“  component.
4. Add at least 6 Sponsors from with different picture sizes. 
7. Click on the Save and Close Button.
8. Go to the Sponsors section preview.
 
 
CURRENT RESULT: 
==================== 
The sponsors logos are not arranged properly in the “Sponsors” section.
https://www.screencast.com/t/A1DflvAoQ 
 
EXPECTED RESULT: 
==================== 
The sponsors logos should be arranged properly in the “Sponsors” section.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build f93b1a9.
