### ISSUE TITLE
The application is not cleaning the fields when the a “Keep in touch” request is made.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#7]
Description: 
The application is not cleaning the fields when the a “Keep in touch” request is made.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the “Contact” section.
3. Fill out all the fields
4. Click on the “Send” Button.
 
CURRENT RESULT: 
==================== 
The registration was done correctly, but the fields were not cleared after clicking the “Send” button.
https://www.screencast.com/t/bT4xEMac 
 
EXPECTED RESULT: 
==================== 
The registration was done correctly, but the fields should be cleared after clicking the “Send” button.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build f2ef5e6.
