### ISSUE TITLE
The application is displaying an error message when more than 1 attachment is added in the “Contact-us” section.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#8]
Description: 
The application is displaying an error message when more than 1 attachment is added in the “Contact-us” section.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. On the site bar, locate the components section.
3. Click on the edit button of the “Contact-us“  component.
4. On the Attachments section add 2 new attachments.
5. Click on the Save and Close Button.
6. Go to the “Contact Us” section preview.
 
 
CURRENT RESULT: 
==================== 
The application displays an error message in the “Contact-us” section.
https://www.screencast.com/t/J3SgRPxR 
 
EXPECTED RESULT: 
==================== 
The application should  not displayed an error message in the “Contact-us” section, or the application should limit to add only 1 attachment.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build b0bc526.
