### ISSUE TITLE
The “Back to top” button is overlapping some footer components in mobile.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-events#9]
Description: 
The “Back to top” button is overlapping some footer components in mobile.
 
-Env:
Device: Android 7.1.1 
Google Chrome Version 58.0.30.29.83
Mozilla Firefox 53.0.2

Device: Iphone 7
Google Chrome Version 58.0.30.29.113
Safari 10.3
Firefox 7.2(2672)

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Event site.
2. Go to the end of the page.
https://www.screencast.com/t/YDumIr1xF 
https://www.screencast.com/t/uuAKmragW 
https://www.screencast.com/t/ZuToHsKmpw 
 

CURRENT RESULT: 
==================== 
The “Back to top” button is overlapping some footer components.
 
EXPECTED RESULT: 
==================== 
The “Back to top” button should not overlapped some footer components.

**Comment by LorenzoRodriguezRivetlogic** [comment]
fixed

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 3753745.
